"""add_twilio_fields

Revision ID: c256d67d97a7
Revises: 6fb5f899698c
Create Date: 2026-03-30 06:51:02.186368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c256d67d97a7'
down_revision: Union[str, None] = '6fb5f899698c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('workspaces', sa.Column('twilio_account_sid', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('twilio_auth_token', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('twilio_whatsapp_number', sa.String(length=30), nullable=True))
    op.add_column('workspaces', sa.Column('whatsapp_provider', sa.String(length=20), nullable=False, server_default='meta'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'whatsapp_provider')
    op.drop_column('workspaces', 'twilio_whatsapp_number')
    op.drop_column('workspaces', 'twilio_auth_token')
    op.drop_column('workspaces', 'twilio_account_sid')
    # ### end Alembic commands ###
